---
- hosts: slave
  become: true 
  tasks:
  - name: Update apt package list
    apt:
      update_cache: yes
        
  - name: add jenkins key 
    apt_key: 
      url:  https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
      state: present 

  - name: add jenkins repo 
    apt_repository: 
      repo: 'deb https://pkg.jenkins.io/debian-stable binary/'
      state: present 

  - name: Install fontconfig and openjdk-17-jre
    apt:
      name:
        - fontconfig
        - openjdk-17-jre
      state: present

  - name: download maven packages 
    get_url:
      url: https://dlcdn.apache.org/maven/maven-3/3.9.6/binaries/apache-maven-3.9.6-bin.tar.gz
      dest: /opt

  - name: extract maven packages 
    unarchive:
      src: /opt/apache-maven-3.9.2-bin.tar.gz
      dest: /opt 
      remote_src: yes