---
- hosts: slave
  become: true 
  tasks:
  - name: Update apt package list
    apt:
      update_cache: yes
        
  - name: Install fontconfig and openjdk-11-jre
    apt:
      name:
        - fontconfig
        - openjdk-11-jre
      state: present

  # - name: download maven packages 
  #   get_url:
  #     url: https://dlcdn.apache.org/maven/maven-3/3.9.6/binaries/apache-maven-3.9.6-bin.tar.gz
  #     dest: /opt
  #     validate_certs: no

  - name: download maven packages 
    ansible.builtin.command: curl -L -o /opt/apache-maven-3.9.6-bin.tar.gz https://dlcdn.apache.org/maven/maven-3/3.9.6/binaries/apache-maven-3.9.6-bin.tar.gz

  - name: extract maven packages 
    unarchive:
      src: /opt/apache-maven-3.9.6-bin.tar.gz
      dest: /opt 
      remote_src: yes